//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCAS.WebApp.MVC {
    
    
    public partial class _Default {
        
        /// <summary>
        /// UC_SlideShowSimple1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UC_SlideShowSimple UC_SlideShowSimple1;
        
        /// <summary>
        /// UC_StudentZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UC_StudentZone UC_StudentZone1;
        
        /// <summary>
        /// UC_StaffZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UC_StaffZone UC_StaffZone1;
        
        /// <summary>
        /// UC_EstablishmentZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UC_EstablishmentZone UC_EstablishmentZone1;
    }
}
