//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro.WebApplication.App_MasterPages {
    
    
    public partial class ICAS {
        
        /// <summary>
        /// Head_ICAS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head_ICAS;
        
        /// <summary>
        /// formICAS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm formICAS;
        
        /// <summary>
        /// WebUserControlMenu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUserControlMenu WebUserControlMenu1;
        
        /// <summary>
        /// ScriptManagerICAS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManagerICAS;
        
        /// <summary>
        /// lit_Welcome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lit_Welcome;
        
        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
        
        /// <summary>
        /// ctrl_PrincipalMessage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTPL.ICAS.WebApplication.App_UserControls.ICAS.PrincipalMessage ctrl_PrincipalMessage1;
        
        /// <summary>
        /// ctrl_StudentZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTPL.ICAS.WebApplication.App_UserControls.ICAS.UC_StudentZone ctrl_StudentZone;
        
        /// <summary>
        /// ctrl_StaffZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTPL.ICAS.WebApplication.App_UserControls.ICAS.UC_StaffZone ctrl_StaffZone1;
        
        /// <summary>
        /// ctrl_EstablishmentZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTPL.ICAS.WebApplication.App_UserControls.ICAS.UC_EstablishmentZone ctrl_EstablishmentZone1;
        
        /// <summary>
        /// UC_LibraryZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTPL.ICAS.WebApplication.App_UserControls.ICAS.UC_LibraryZone UC_LibraryZone1;
        
        /// <summary>
        /// ctrl_AlumniZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTPL.ICAS.WebApplication.App_UserControls.ICAS.UC_AlumniZone ctrl_AlumniZone1;
        
        /// <summary>
        /// ctrl_WebFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LTPL.ICAS.WebApplication.App_UserControls.ICAS.UC_WebFooter ctrl_WebFooter;
    }
}
